[server]
maxUploadSize = 10
headless = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"

[theme]
base = "light"
primaryColor = "#234F84"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F2F5F9"
textColor = "#172B43"
font = "sans serif"
